version: "3"

services:
  anakonda:
    build: .
    image: anakonda:latest
    restart: unless-stopped
    env_file: .env
    expose:
      - 8080/tcp
    networks:
      - db

  mysql:
    image: mysql:8
    restart: unless-stopped
    env_file: .env
    expose:
      - 3306/tcp
    networks:
      - db
    volumes:
      - mysqldata:/var/lib/mysql

networks:
  db:

volumes:
  mysqldata:
